micronaut:
  application:
    name: MessengerChatGptBot
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: $JWT_GENERATOR_SIGNATURE_SECRET
    intercept-url-map:
    - access: isAnonymous()
      pattern: /swagger/**
    - access: isAnonymous()
      pattern: /swagger-ui/**
  server:
    port: 8080
    netty:
      access-logger:
        enabled: true
        log-format: common
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
open-ai:
  token: $OPEN_AI_TOKEN
  gpt-model: ${$OPEN_AI_GPT_MODEL:gpt-3.5-turbo}
meta:
  app-id: $META_APP_ID
  token: $META_APP_TOKEN
